version: '3'

services:
  puddlee:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - ./config:/app/config
    command: ["./puddlee", "serve"]
