// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
	}
	// MessagesColumns holds the columns for the "messages" table.
	MessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "payload", Type: field.TypeString},
		{Name: "user_messages", Type: field.TypeInt},
	}
	// MessagesTable holds the schema information for the "messages" table.
	MessagesTable = &schema.Table{
		Name:       "messages",
		Columns:    MessagesColumns,
		PrimaryKey: []*schema.Column{MessagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "messages_users_messages",
				Columns:    []*schema.Column{MessagesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// RoomsColumns holds the columns for the "rooms" table.
	RoomsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "title", Type: field.TypeString},
		{Name: "is_completed", Type: field.TypeBool, Default: false},
		{Name: "category_rooms", Type: field.TypeInt, Nullable: true},
		{Name: "user_own_rooms", Type: field.TypeInt, Nullable: true},
	}
	// RoomsTable holds the schema information for the "rooms" table.
	RoomsTable = &schema.Table{
		Name:       "rooms",
		Columns:    RoomsColumns,
		PrimaryKey: []*schema.Column{RoomsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "rooms_categories_rooms",
				Columns:    []*schema.Column{RoomsColumns[5]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "rooms_users_own_rooms",
				Columns:    []*schema.Column{RoomsColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "profile_img", Type: field.TypeString, Nullable: true},
		{Name: "password", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// VerificationsColumns holds the columns for the "verifications" table.
	VerificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "uuid", Type: field.TypeUUID, Unique: true},
		{Name: "code", Type: field.TypeString},
		{Name: "expired_at", Type: field.TypeTime},
	}
	// VerificationsTable holds the schema information for the "verifications" table.
	VerificationsTable = &schema.Table{
		Name:       "verifications",
		Columns:    VerificationsColumns,
		PrimaryKey: []*schema.Column{VerificationsColumns[0]},
	}
	// ViewsColumns holds the columns for the "views" table.
	ViewsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "filepath", Type: field.TypeString},
		{Name: "room_views", Type: field.TypeInt},
	}
	// ViewsTable holds the schema information for the "views" table.
	ViewsTable = &schema.Table{
		Name:       "views",
		Columns:    ViewsColumns,
		PrimaryKey: []*schema.Column{ViewsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "views_rooms_views",
				Columns:    []*schema.Column{ViewsColumns[4]},
				RefColumns: []*schema.Column{RoomsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// RoomMessagesColumns holds the columns for the "room_messages" table.
	RoomMessagesColumns = []*schema.Column{
		{Name: "room_id", Type: field.TypeInt},
		{Name: "message_id", Type: field.TypeInt},
	}
	// RoomMessagesTable holds the schema information for the "room_messages" table.
	RoomMessagesTable = &schema.Table{
		Name:       "room_messages",
		Columns:    RoomMessagesColumns,
		PrimaryKey: []*schema.Column{RoomMessagesColumns[0], RoomMessagesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "room_messages_room_id",
				Columns:    []*schema.Column{RoomMessagesColumns[0]},
				RefColumns: []*schema.Column{RoomsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "room_messages_message_id",
				Columns:    []*schema.Column{RoomMessagesColumns[1]},
				RefColumns: []*schema.Column{MessagesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserParticipantRoomsColumns holds the columns for the "user_participant_rooms" table.
	UserParticipantRoomsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "room_id", Type: field.TypeInt},
	}
	// UserParticipantRoomsTable holds the schema information for the "user_participant_rooms" table.
	UserParticipantRoomsTable = &schema.Table{
		Name:       "user_participant_rooms",
		Columns:    UserParticipantRoomsColumns,
		PrimaryKey: []*schema.Column{UserParticipantRoomsColumns[0], UserParticipantRoomsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_participant_rooms_user_id",
				Columns:    []*schema.Column{UserParticipantRoomsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_participant_rooms_room_id",
				Columns:    []*schema.Column{UserParticipantRoomsColumns[1]},
				RefColumns: []*schema.Column{RoomsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CategoriesTable,
		MessagesTable,
		RoomsTable,
		UsersTable,
		VerificationsTable,
		ViewsTable,
		RoomMessagesTable,
		UserParticipantRoomsTable,
	}
)

func init() {
	MessagesTable.ForeignKeys[0].RefTable = UsersTable
	RoomsTable.ForeignKeys[0].RefTable = CategoriesTable
	RoomsTable.ForeignKeys[1].RefTable = UsersTable
	ViewsTable.ForeignKeys[0].RefTable = RoomsTable
	RoomMessagesTable.ForeignKeys[0].RefTable = RoomsTable
	RoomMessagesTable.ForeignKeys[1].RefTable = MessagesTable
	UserParticipantRoomsTable.ForeignKeys[0].RefTable = UsersTable
	UserParticipantRoomsTable.ForeignKeys[1].RefTable = RoomsTable
}
