// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PUDDLEEE/puddleee_back/ent/room"
	"github.com/PUDDLEEE/puddleee_back/ent/view"
)

// ViewCreate is the builder for creating a View entity.
type ViewCreate struct {
	config
	mutation *ViewMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (vc *ViewCreate) SetCreateTime(t time.Time) *ViewCreate {
	vc.mutation.SetCreateTime(t)
	return vc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (vc *ViewCreate) SetNillableCreateTime(t *time.Time) *ViewCreate {
	if t != nil {
		vc.SetCreateTime(*t)
	}
	return vc
}

// SetUpdateTime sets the "update_time" field.
func (vc *ViewCreate) SetUpdateTime(t time.Time) *ViewCreate {
	vc.mutation.SetUpdateTime(t)
	return vc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (vc *ViewCreate) SetNillableUpdateTime(t *time.Time) *ViewCreate {
	if t != nil {
		vc.SetUpdateTime(*t)
	}
	return vc
}

// SetFilepath sets the "filepath" field.
func (vc *ViewCreate) SetFilepath(s string) *ViewCreate {
	vc.mutation.SetFilepath(s)
	return vc
}

// SetRoomID sets the "room" edge to the Room entity by ID.
func (vc *ViewCreate) SetRoomID(id int) *ViewCreate {
	vc.mutation.SetRoomID(id)
	return vc
}

// SetRoom sets the "room" edge to the Room entity.
func (vc *ViewCreate) SetRoom(r *Room) *ViewCreate {
	return vc.SetRoomID(r.ID)
}

// Mutation returns the ViewMutation object of the builder.
func (vc *ViewCreate) Mutation() *ViewMutation {
	return vc.mutation
}

// Save creates the View in the database.
func (vc *ViewCreate) Save(ctx context.Context) (*View, error) {
	vc.defaults()
	return withHooks(ctx, vc.sqlSave, vc.mutation, vc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (vc *ViewCreate) SaveX(ctx context.Context) *View {
	v, err := vc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vc *ViewCreate) Exec(ctx context.Context) error {
	_, err := vc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vc *ViewCreate) ExecX(ctx context.Context) {
	if err := vc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (vc *ViewCreate) defaults() {
	if _, ok := vc.mutation.CreateTime(); !ok {
		v := view.DefaultCreateTime()
		vc.mutation.SetCreateTime(v)
	}
	if _, ok := vc.mutation.UpdateTime(); !ok {
		v := view.DefaultUpdateTime()
		vc.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vc *ViewCreate) check() error {
	if _, ok := vc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "View.create_time"`)}
	}
	if _, ok := vc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "View.update_time"`)}
	}
	if _, ok := vc.mutation.Filepath(); !ok {
		return &ValidationError{Name: "filepath", err: errors.New(`ent: missing required field "View.filepath"`)}
	}
	if v, ok := vc.mutation.Filepath(); ok {
		if err := view.FilepathValidator(v); err != nil {
			return &ValidationError{Name: "filepath", err: fmt.Errorf(`ent: validator failed for field "View.filepath": %w`, err)}
		}
	}
	if _, ok := vc.mutation.RoomID(); !ok {
		return &ValidationError{Name: "room", err: errors.New(`ent: missing required edge "View.room"`)}
	}
	return nil
}

func (vc *ViewCreate) sqlSave(ctx context.Context) (*View, error) {
	if err := vc.check(); err != nil {
		return nil, err
	}
	_node, _spec := vc.createSpec()
	if err := sqlgraph.CreateNode(ctx, vc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	vc.mutation.id = &_node.ID
	vc.mutation.done = true
	return _node, nil
}

func (vc *ViewCreate) createSpec() (*View, *sqlgraph.CreateSpec) {
	var (
		_node = &View{config: vc.config}
		_spec = sqlgraph.NewCreateSpec(view.Table, sqlgraph.NewFieldSpec(view.FieldID, field.TypeInt))
	)
	if value, ok := vc.mutation.CreateTime(); ok {
		_spec.SetField(view.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := vc.mutation.UpdateTime(); ok {
		_spec.SetField(view.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := vc.mutation.Filepath(); ok {
		_spec.SetField(view.FieldFilepath, field.TypeString, value)
		_node.Filepath = value
	}
	if nodes := vc.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   view.RoomTable,
			Columns: []string{view.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.room_views = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ViewCreateBulk is the builder for creating many View entities in bulk.
type ViewCreateBulk struct {
	config
	err      error
	builders []*ViewCreate
}

// Save creates the View entities in the database.
func (vcb *ViewCreateBulk) Save(ctx context.Context) ([]*View, error) {
	if vcb.err != nil {
		return nil, vcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(vcb.builders))
	nodes := make([]*View, len(vcb.builders))
	mutators := make([]Mutator, len(vcb.builders))
	for i := range vcb.builders {
		func(i int, root context.Context) {
			builder := vcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ViewMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, vcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, vcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, vcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (vcb *ViewCreateBulk) SaveX(ctx context.Context) []*View {
	v, err := vcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vcb *ViewCreateBulk) Exec(ctx context.Context) error {
	_, err := vcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vcb *ViewCreateBulk) ExecX(ctx context.Context) {
	if err := vcb.Exec(ctx); err != nil {
		panic(err)
	}
}
