// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	ent "github.com/PUDDLEEE/puddleee_back/ent"

	mock "github.com/stretchr/testify/mock"

	roomdto "github.com/PUDDLEEE/puddleee_back/internal/room/dto"
)

// IRoomRepository is an autogenerated mock type for the IRoomRepository type
type IRoomRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1, _a2
func (_m *IRoomRepository) Create(_a0 context.Context, _a1 *ent.Client, _a2 roomdto.CreateRoomDTO) (*ent.Room, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *ent.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ent.Client, roomdto.CreateRoomDTO) (*ent.Room, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ent.Client, roomdto.CreateRoomDTO) *ent.Room); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ent.Client, roomdto.CreateRoomDTO) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: _a0, _a1, _a2
func (_m *IRoomRepository) Delete(_a0 context.Context, _a1 *ent.Client, _a2 int) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ent.Client, int) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: _a0, _a1
func (_m *IRoomRepository) Find(_a0 context.Context, _a1 *ent.Client) ([]*ent.Room, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []*ent.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ent.Client) ([]*ent.Room, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ent.Client) []*ent.Room); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ent.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ent.Client) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOneById provides a mock function with given fields: _a0, _a1, _a2
func (_m *IRoomRepository) FindOneById(_a0 context.Context, _a1 *ent.Client, _a2 int) (*ent.Room, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for FindOneById")
	}

	var r0 *ent.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ent.Client, int) (*ent.Room, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ent.Client, int) *ent.Room); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ent.Client, int) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *IRoomRepository) Update(_a0 context.Context, _a1 *ent.Client, _a2 int, _a3 roomdto.UpdateRoomDTO) (*ent.Room, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *ent.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ent.Client, int, roomdto.UpdateRoomDTO) (*ent.Room, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ent.Client, int, roomdto.UpdateRoomDTO) *ent.Room); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ent.Client, int, roomdto.UpdateRoomDTO) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIRoomRepository creates a new instance of IRoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRoomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRoomRepository {
	mock := &IRoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
