// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"context"
	"github.com/PUDDLEEE/puddleee_back/ent"
)

// Injectors from wire.go:

func InitializeController(ctx context.Context, client *ent.Client) UserController {
	userRepository := NewUserRepository()
	userService := NewService(userRepository, ctx, client)
	userController := NewController(userService)
	return userController
}
